# Generated by Django 4.2.11 on 2026-04-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windowdoordesign',
            name='glass_type',
            field=models.CharField(blank=True, choices=[('clear', 'Clear Glass'), ('tinted', 'Tinted Glass'), ('frosted', 'Frosted Glass'), ('double_glazed', 'Double Glazed'), ('tempered', 'Tempered Glass')], max_length=20, null=True),
        ),
    ]
