# Generated by Django 4.2.11 on 2026-04-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_system', '0002_alter_windowdoordesign_glass_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windowdoordesign',
            name='type_choice',
            field=models.CharField(choices=[('window', 'Window'), ('door', 'Door')], max_length=20),
        ),
    ]
