# Generated by Django 4.2.11 on 2026-04-16 16:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('aluminum', 'Aluminum'), ('upvc', 'UPVC'), ('steel', 'Steel'), ('wood', 'Wood')], max_length=20)),
                ('rate_per_sqft', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('labor_cost_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('glass_cost_per_sqft', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('mesh_cost_per_sqft', models.DecimalField(decimal_places=2, default=50, max_digits=10)),
                ('profile_cost_per_meter', models.DecimalField(decimal_places=2, default=150, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Pricing Rates',
            },
        ),
        migrations.CreateModel(
            name='WindowDoorDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('width', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('height', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('type_choice', models.CharField(choices=[('sliding', 'Sliding'), ('casement', 'Casement'), ('awning', 'Awning'), ('tilt_turn', 'Tilt & Turn'), ('fixed', 'Fixed'), ('bifold', 'Bifold'), ('revolving', 'Revolving')], max_length=20)),
                ('glass_type', models.CharField(choices=[('clear', 'Clear Glass'), ('tinted', 'Tinted Glass'), ('frosted', 'Frosted Glass'), ('double_glazed', 'Double Glazed'), ('tempered', 'Tempered Glass')], max_length=20)),
                ('has_mesh', models.BooleanField(default=False)),
                ('finish_type', models.CharField(choices=[('anodized', 'Anodized'), ('powder_coated', 'Powder Coated'), ('raw', 'Raw'), ('painted', 'Painted'), ('natural_wood', 'Natural Wood')], max_length=20)),
                ('number_of_units', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('material', models.CharField(choices=[('aluminum', 'Aluminum'), ('upvc', 'UPVC'), ('steel', 'Steel'), ('wood', 'Wood')], default='aluminum', max_length=20)),
                ('total_area', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=10)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Window/Door Designs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('quotation', 'Quotation'), ('boq', 'Bill of Quantities'), ('cutting_list', 'Cutting List'), ('material_summary', 'Material Summary')], max_length=20)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/%d/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='design_system.windowdoordesign')),
            ],
            options={
                'verbose_name_plural': 'Design Reports',
            },
        ),
    ]
